title: Sunil Mourya
description: Rust developer & runner sharing my journey
url: https://sunilmourya.github.io
baseurl: ""
author:
  name: Sunil Mourya
  email: sunil_mourya@outlook.com
  github: sunilmourya
  linkedin: sunilmourya

# Blog settings
permalink: /blog/:year/:month/:day/:title/
paginate: 10
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
theme: minima

# Collections
collections:
  posts:
    output: true